### ISSUE TITLE
Sandbox Squareup

### ISSUE THREAD

**Issue by dheeraj1996** [square/in-app-payments-ios#11]
I have added **ASquareInAppPaymentsSDK** SDK in my app. And in backend and frontend both have Sandbox mode. I have done setup according to given documentation which links are following.
**https://developer.squareup.com/docs/in-app-payments-sdk/build-on-ios**
**https://developer.squareup.com/docs/in-app-payments-sdk/cookbook/connect-to-a-backend-service**

now the concern is that I am not able to add the card when I am using **sandbox application id** and showing error "invalid_application_id".

**Comment by StephenJosey** [comment]
Hi @dheeraj1996 just to confirm, you're setting the application id in your mobile application before attempting any other In-App Payments functionality, correct? (https://developer.squareup.com/docs/api/in-app-payment/ios/Classes/SQIPInAppPaymentsSDK.html#/c:objc(cs)SQIPInAppPaymentsSDK(cpy)squareApplicationID)

Are you also able to confirm that you're using the application id and not the access token from your Square dashboard?

**Comment by dheeraj1996** [comment]
**Thanks for responding**
Yes I am using sandbox application id (**sandbox-sq******************ww**)  which is got by switching on **sandbox setting** .

let you know what I have done in my application till now to integrate **ASquareInAppPaymentsSDK**

**In app Delegate**

import SquareInAppPaymentsSDK
@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions:
        [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        // Setted my sandbox application id
        SQIPInAppPaymentsSDK.squareApplicationID = **sandbox-sq******************ww**
        return true
    }
}
**In delegate method**
import SquareInAppPaymentsSDK

extension <MyViewController>: SQIPCardEntryViewControllerDelegate { 
    func showCardEntryForm() {
        let theme = SQIPTheme()
        theme.tintColor = .green
        theme.saveButtonTitle = "Submit"
        let cardEntryForm = SQIPCardEntryViewController(theme: theme)
        cardEntryForm.delegate = self
        let navigationController = UINavigationController(rootViewController: cardEntryForm)
        present(navigationController, animated: true, completion: nil)
    }

    func cardEntryViewController(_ cardEntryViewController: SQIPCardEntryViewController,
                                 didCompleteWith status: SQIPCardEntryCompletionStatus) {
dismiss(animated: true, completion: nil)
  }
    
    func cardEntryViewController(_ cardEntryViewController: SQIPCardEntryViewController,
                                 didObtain cardDetails: SQIPCardDetails,
                                 completionHandler: @escaping (Error?) -> Void) {

self.processPayment(

        cardDetails.nonce) {

            (transactionID, errorDescription) in

            guard let errorDescription = errorDescription else {
        
                completionHandler(nil)

                return
            }
            let error = NSError(
                //domain: "com.example.supercookie",

                code: 0,

                userInfo:[NSLocalizedDescriptionKey : errorDescription])

                completionHandler(error)

    }
 
    }
}
func processPayment(
        _ nonce: String,
        completion: @escaping (String?, String?) -> Void) {
        
        let url = URL(string: https://****.com.au)!
        
        var request = URLRequest(url: url)
        request.httpMethod = "POST"
        let json = ["card_nonce": nonce,"make_default" : true] as [String : Any]

        let httpBody = try? JSONSerialization.data(withJSONObject: json)

        request.addValue("Application/json", forHTTPHeaderField: "Content-Type")
        request.httpBody = httpBody
       
        URLSession.shared.dataTask(with: request) { data, response, error in
            if let error = error as NSError?{
                if error.domain == NSURLErrorDomain {
                    DispatchQueue.main.async {
                        completion("", "Could not contact host")
                    }
                } else {
                    DispatchQueue.main.async {
                        completion("", "Something went wrong")
                    }
                }
            } else if let data = data {
                do {
                    let json = try JSONSerialization.jsonObject(
                        with: data,
                        options: []) as! [String: Any]
                    if let httpResponse = response as? HTTPURLResponse,
                        httpResponse.statusCode == 200 {
                        DispatchQueue.main.async {
                            
                           
                            completion("success", nil)
                        }
                    } else {
                        DispatchQueue.main.async {
                            completion("", json["errorMessage"] as? String)
                        }
                    }
                } catch {
                    DispatchQueue.main.async {
                        completion("", "Failure")
                    }
                }
            }
            }.resume()
    }

and finally, I got response **invalid_application_id**.

**Comment by MikeSilvis** [comment]
Your backend needs to hit `squareupsandbox` instead of `squareup` when you attempt to charge the nonce generated from Sandbox
