### ISSUE TITLE
SquareInAppPaymentsSDK 1.3.0 warns against use in app extension

### ISSUE THREAD

**Issue by mthole** [square/in-app-payments-ios#17]
We use SquareInAPpPaymentsSDK in an app extension, but the latest update (v1.3.0) now causes a warning at linker time:

```
ld: warning: linking against a dylib which is not safe for use in application extensions: [snip]/Pods/SquareInAppPaymentsSDK/SquareInAppPaymentsSDKs.framework/SquareInAppPaymentsSDK.framework/SquareInAppPaymentsSDK
```

**Comment by StephenJosey** [comment]
Sorry for the delay in follow-up. This is a known warning and we are looking into resolving it. We'll let you know once it's been fixed. Thanks for reporting!

**Comment by StephenJosey** [comment]
Resolved in newer versions
