### ISSUE TITLE
Unable to retrieve nonce

### ISSUE THREAD

**Issue by KamleshShingarakhiya** [square/in-app-payments-ios#18]
Hello I am using in-app-payments-ios in iOS. I getting successfully get cardDetails.nonce but I can not take payment with this and getting bad request.

curl -X POST \
-H 'Accept: application/json' \
-H 'Authorization: Bearer {{access_token_removed}}' \
-H 'Cache-Control: no-cache' \
-H 'Content-Type: application/json' \
-d '{
    "idempotency_key": "3A81BB53-A1BE-4100-8A9A-3D584D85A757",
    "autocomplete": true,
    "amount_money": {
      "amount": 255,
      "currency": "USD"
    },
    "source_id": "cnon:CBASEFlwxg3bRkcAigr58wVrmu8"
    }
}' \
'https://connect.squareupsandbox.com/v2/payments'

**Comment by StephenJosey** [comment]
Hi @KamleshShingarakhiya sorry for the delay. Were you able to figure this out? If not, what error message are you receiving?

**Comment by StephenJosey** [comment]
Going to go ahead and close this due to no response. Please comment and I can reopen if you're still encountering this error.
