### ISSUE TITLE
Catalyst Support

### ISSUE THREAD

**Issue by sincaleb** [square/in-app-payments-ios#19]
When building for Mac Catalyst using the framework installed via CocoaPods I get this error: `building for Mac Catalyst, but linking in dylib built for iOS Simulator`. I'm assuming this is because there isn't a build for catalyst included. Is it possible to include one, or do I need to do something else to target the correct framework?

**Comment by StephenJosey** [comment]
Thanks for reporting. I'll pass this feedback to our iOS team, but I don't believe we have Catalyst support at this time.

**Comment by PLJNS** [comment]
I would be interested in this feature.

**Comment by PLJNS** [comment]
Not that it's necessarily indicative of being able to function in production, but I would like to point out that the library works in the x86 simulator, which is a strong sign it can fairly easily support x86 Catalyst. For an example of a major 3rd party library done well, Firebase is a good reference point.
