### ISSUE TITLE
[1.4.0] Carthage Support Broken

### ISSUE THREAD

**Issue by joshluongo** [square/in-app-payments-ios#22]
In version 1.4.0 support for Carthage appears to be broken, when adding it to the `Cartfile` and then running `carthage update` it doesn't seem to find the frameworks and thus doesn't unpack anything.

Here is a repo on v1.4.0 showing the issue https://github.com/joshluongo/in-app-payments-ios-test/tree/v1.4.0

Here is the same repo on v1.3.0 which works fine https://github.com/joshluongo/in-app-payments-ios-test/tree/v1.3.0

### 1.40 Carthage Update
```
*** Checking out in-app-payments-ios at "1.4.0"
*** xcodebuild output can be found in /var/folders/18/77v22xqn2zv5ddqgrlwnxht40000gn/T/carthage-xcodebuild.M6umqd.log
*** Downloading in-app-payments-ios.framework binary at "1.4.0"
```

### 1.3.0 Carthage Update
```
*** Checking out in-app-payments-ios at "1.3.0"
*** xcodebuild output can be found in /var/folders/18/77v22xqn2zv5ddqgrlwnxht40000gn/T/carthage-xcodebuild.ShY95n.log
*** Downloading in-app-payments-ios.framework binary at "Adds support for Strong Customer Authentication"
```

**Comment by StephenJosey** [comment]
This should be working, now. Going to close this, but please leave a comment if it's still not working and I can re-open to investigate. Thanks for reporting!
