### ISSUE TITLE
SPM support

### ISSUE THREAD

**Issue by svedm** [square/in-app-payments-ios#24]
What's about SPM & xcframework support? Is it in the roadmap?

**Comment by StephenJosey** [comment]
xcframework should be supported as of the release today. I will relay SPM support to the team, thanks for asking!

**Comment by bdrelling** [comment]
This issue has been open for 10 months. What's the status on this? Square is the last holdout in CocoaPods in our project. I'm sure I'm not alone in saying that a lack of SPM support is enough to have me considering a new payment processor.

**Comment by bdrelling** [comment]
CC @StephenJosey @MikeSilvis do you have any news around SPM support?

**Comment by MikeSilvis** [comment]
Hi @bdrelling we have not yet been able to prioritize adding SPM support. It should be relatively straight forward however to add if you want to submit a PR against the repo.

**Comment by bdrelling** [comment]
@MikeSilvis I'm absolutely happy to help and open a PR if I find the time -- if I do so, can someone on your team commit to reasonable turnaround time for reviewing/approving the work and getting it integrated?

I only ask because sometimes outside contributions are requested, but never addressed or take weeks/months to address, which can make the PR stale and never integrate the work, etc. -- just results in a lot of wasted time on behalf of the author, which is really unfortunate. 😞

**Comment by JamieScanlon** [comment]
Upvote for prioritizing SPM support. This is the last SDK preventing us from removing CocoaPods as a dependancy.

**Comment by MikeSilvis** [comment]
> 

Absolutely, i'll be sure the work gets pushed through!

**Comment by bdrelling** [comment]
I was curious about the work effort so I investigated a bit this morning. Here's some results:

I can extract the `.xcframework` files from the `.zip` and distribute manually via SPM, which works just fine. This would require including the `.xcframework` file in the repository. This is fairly typical, but also not required--I know many other libraries do what you're trying to accomplish.

However, there are two issues around hosting your binaries right now that I'm unable to solve:

1. Currently, this repo is hosting two XCFrameworks under one `.zip`. I don't believe this is recommended for CocoaPods, but also don't think it's supported by SPM.
2. Even with taking the framework out of the zip, putting into its own zip (either at root level or wrapped by another directory), and generating a checksum, Xcode fails to download the `.zip` properly.

@MikeSilvis I'll connect with you via Slack after Thanksgiving Break, and will open a PR at some point at least demonstrating what I've done and maybe that'll help jumpstart the work here.

If you'd be willing to keep the framework in the repo even as a stop-gap, I could open a PR immediately with SPM support as well. I'll get both up as an example as to what's going on as well.

**References**
- https://developer.apple.com/documentation/swift_packages/distributing_binary_frameworks_as_swift_packages
- https://betterprogramming.pub/how-to-add-compiled-frameworks-in-swift-package-manager-f0cdbde84fc7
- https://medium.com/paypal-tech/adding-swift-package-manager-support-to-the-braintree-ios-sdk-972961636d9b

**Comment by MikeSilvis** [comment]
SPM is now supported!
