### ISSUE TITLE
Preview not working in xcode 14

### ISSUE THREAD

**Issue by thanakijwanavit** [square/in-app-payments-ios#40]
I keep getting the missing executable error while trying to preview my app in xcode. Removing the library solves the problem.

 ```    SettingsError: noExecutablePath(<IDESwiftPackageStaticLibraryProductBuildable:ObjectIdentifier(0x0000600005cd1b00):'SquareBuyerVerificationSDK'>)```

[previews_diagnostics_summary.txt](https://github.com/square/in-app-payments-ios/files/9603289/previews_diagnostics_summary.txt)

**Comment by joshluongo** [comment]
Are you running Xcode under rosetta? If not that may explain the issue as this framework doesn't work on ARM macs. I raised this under #35 , you can patch the framework to make it work but its more of a bandaid solution.

**Comment by brandonjenniges** [comment]
Please update to 1.6.3 and let us know if you're still having an issue. We removed the exclusion of M1 macs for simulator in the latest release.
