### ISSUE TITLE
Cannot build 1.6.0 for AppStore

### ISSUE THREAD

**Issue by OJDee** [square/in-app-payments-ios#47]
Using Swift Package Manager, 1.5.8 works fine

Updated to 1.6.0

Uploading to Appstore connect returns multiple instances of:

`x.app/Frameworks/SquareInAppPaymentsSDK.framework/setup” is not properly signed.`

`The bundle at 'x.app/Frameworks/SquareInAppPaymentsSDK.framework' contains disallowed nested bundles`

`The bundle at 'x.app/Frameworks/SquareBuyerVerificationSDK.framework' contains disallowed file 'Frameworks'`

Have added build script, as per documentation:

`if [ "${CONFIGURATION}" = "Release" ]; then
FRAMEWORKS="${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}"
"${FRAMEWORKS}/SquareInAppPaymentsSDK.framework/setup"
fi`

Requires 'Release' check or will not build for development either.

**Comment by brandonjenniges** [comment]
This should be fixed in 1.6.3. There were improvements made in regards to Swift Package Manager support.  Please update your build script to be:

```
SETUP_SCRIPT=${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}"/SquareInAppPaymentsSDK.framework/setup"
if [ -f "$SETUP_SCRIPT" ]; then
  "$SETUP_SCRIPT"
fi
```
Let us know if you're still facing any issue, thanks.
