### ISSUE TITLE
SquareInAppPaymentsSDK Version 1.6.0 not working

### ISSUE THREAD

**Issue by Dual-Tech** [square/in-app-payments-ios#49]
Using cocoapods SquareInAppPaymentsSDK version 1.6.0

The project builds and installs with no issue on physical devices and simulators, project crashes as soon the launch screen goes away. Below is the output from the xcode logs.

I downgraded to version 1.5.8 and had no issues.

please advise

dyld[4489]: Library not loaded: @rpath/CorePaymentCard.framework/CorePaymentCard
  Referenced from: <9CBFF902-6672-33E7-A883-8A5A47C75573> /Users/dt/Library/Developer/CoreSimulator/Devices/abc123/data/Containers/Bundle/Application/qwerty123/Project1.app/Frameworks/SquareInAppPaymentsSDK.framework/SquareInAppPaymentsSDK
  Reason: tried: '/Users/dt/Library/Developer/Xcode/DerivedData/Project1-byzlyabaqbqvfkbhoeeyuvdogmxk/Build/Products/Debug-iphonesimulator/CorePaymentCard.framework/CorePaymentCard' (errno=2), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/CorePaymentCard.framework/CorePaymentCard' (errno=2), '/usr/lib/swift/CorePaymentCard.framework/CorePaymentCard' (errno=2, no dyld cache), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/CorePaymentCard.framework/CorePaymentCard' (errno=2), '/usr/lib/swift/CorePaymentCard.framework/CorePaymentCard' (errno=2, no dyld cache), '/Users/dt/Library/Developer/CoreSimulator/Devices/abc123/data/Containers/Bundle/Application/qwerty123/Project1.app/Frameworks/CorePaymentCard.framework/CorePaymentCard' (errno=2), '/Users/dt/Library/Developer/CoreSimulator/Devices/abc123/data/Containers/Bundle/Application/qwerty123/Project1.app/Frameworks/CorePaymentCard.framework/CorePaymentCard' (errno=2), '/Users/dt/Library/Developer/CoreSimulator/Devices/abc123/data/Containers/Bundle/Application/qwerty123/Project1.app/Frameworks/CorePaymentCard.framework/CorePaymentCard' (errno=2), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/CorePaymentCard.framework/CorePaymentCard' (errno=2), '/usr/lib/swift/CorePaymentCard.framework/CorePaymentCard' (errno=2, no dyld cache), '/Users/dt/Library/Developer/CoreSimulator/Devices/abc123/data/Containers/Bundle/Application/qwerty123/Project1.app/Frameworks/CorePaymentCard.framework/CorePaymentCard' (errno=2), '/Users/dt/Library/Developer/CoreSimulator/Devices/abc123/data/Containers/Bundle/Application/qwerty123/Project1.app/Frameworks/CorePaymentCard.framework/CorePaymentCard' (errno=2), '/Users/dt/Library/Developer/CoreSimulator/Devices/abc123/data/Containers/Bundle/Application/qwerty123/Project1.app/Frameworks/CorePaymentCard.framework/CorePaymentCard' (errno=2), '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CorePaymentCard.framework/CorePaymentCard' (errno=2)
Message from debugger: Terminated due to signal 6

**Comment by jyotikdev** [comment]
hi @Dual-Tech , New build script has been added. Once you do that this error goes away: https://github.com/square/in-app-payments-ios#add-build-phase-to-setup-the-squareinapppaymentssdk-andor-squarebuyerverificationsdk-framework
