### ISSUE TITLE
How to pay money to some one directly?

### ISSUE THREAD

**Issue by wutieguo** [square/in-app-payments-ios#5]
I am going to build the Barber app.  
I want the customer to pay money to barber directly on my app.  
how can I integrate Square SDK?
what is transfer API?

**Comment by StephenJosey** [comment]
If you plan on doing in-person payments, then you want to look into our ReaderSDK: https://docs.connect.squareup.com/payments/readersdk/what-it-does. It will allow you to take payments using Square hardware from your custom-made app.

If you want to allow customers to download your app and pay without Square hardware, then you're in the right place (In-App Payments SDK). For more information please see our documentation here: https://docs.connect.squareup.com/payments/in-app-payments-sdk/what-it-does

If you have further questions about either of these SDKs, please feel free to respond and I'll help you out!
