### ISSUE TITLE
apple silicon mac support for app store

### ISSUE THREAD

**Issue by thanakijwanavit** [square/in-app-payments-ios#52]
I uploaded a binary to appstore but got rejected with following message
```
Dear Developer,

We identified one or more issues with a recent delivery for your app, "xxxxxx?. Your delivery was successful, but you may wish to correct the following issues in your next delivery:

ITMS-90863: Apple silicon Macs support issue - The app links with libraries that are not present on Mac:

@rpath/CorePaymentCard.framework/CorePaymentCard
@rpath/ThreeDS_SDK.framework/ThreeDS_SDK

After you’ve corrected the issues, you can upload a new binary to App Store Connect.

Best regards,

The App Store Team
```

**Comment by joshluongo** [comment]
From: [README.md](https://github.com/square/in-app-payments-ios)
> iPhone and iPad apps on Mac with Apple silicon
> 
> Square In-App Payments iOS SDK currently does not support iPhone and iPad apps on Mac with Apple silicon.
>

**Comment by brandonjenniges** [comment]
There is currently no support for using this SDK on Mac. The message you received should've been just a warning and not an app store rejection.
